# Generated by Django 6.0 on 2025-12-17 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Ejercicio')),
                ('descipcion', models.TextField(verbose_name='Descripción')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video de referencia')),
                ('dificultad', models.CharField(choices=[('PRINCIPIANTE', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], default='PRINCIPIANTE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Rutina')),
                ('descripcion', models.TextField(blank=True)),
                ('nivel', models.CharField(choices=[('PRINCIPIANTE', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], max_length=20, verbose_name='Nivel')),
                ('objetivo', models.CharField(choices=[('PERDIDA_PESO', 'Pérdida de Peso'), ('GANANCIA_MUSCULAR', 'Ganancia Muscular'), ('RESISTENCIA', 'Resistencia / Cardio'), ('FLEXIBILIDAD', 'Flexibilidad')], max_length=20, verbose_name='Objetivo')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de finalización')),
                ('duracion_minutos', models.PositiveIntegerField(help_text='Tiempo que tomó completar la rutina', verbose_name='Duración (minutos)')),
                ('notas', models.TextField(blank=True, help_text='¿Cómo se sintió el usuario?', verbose_name='Notas del usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to=settings.AUTH_USER_MODEL)),
                ('rutina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ActivaFit.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(default=3, verbose_name='Series')),
                ('reps', models.PositiveIntegerField(default=10, verbose_name='Repeticiones')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden en la rutina')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ActivaFit.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ActivaFit.rutina')),
            ],
            options={
                'verbose_name': 'Ejercicio de Rutina',
                'verbose_name_plural': 'Ejercicios de la Rutina',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(related_name='routines', through='ActivaFit.RutinaEjercicio', to='ActivaFit.ejercicio'),
        ),
        migrations.AddConstraint(
            model_name='rutinaejercicio',
            constraint=models.UniqueConstraint(fields=('rutina', 'ejercicio'), name='unique_ejercicio_per_rutina'),
        ),
    ]
